### ISSUE TITLE
Trackpad suddenly stops working

### ISSUE THREAD

**Issue by Hologos** [Hologos/hackintosh-hp-elitebook-840-g3#1]
I don't know why yet, but trackpad suddenly stops working sometimes.

The workaround is to connect a mouse via USB or to run an app called TrackpadFix.app, which is an automator script to disable and re-enable "Ignore built-in trackpad when mouse or wireless trackpad is present".

You need to allow the app in `Accessibility` in `Privacy` tab in `Security & Privacy` preferences.

**Do it before you really need it!**

When Trackpad stops working, run the app via **Spotlight**.

*To check, what this app does, look at `Apps/TrackpadFix.app/Contents/document.wflow`.*

**Comment by Hologos** [comment]
To check, what this app does, look at `Apps/TrackpadFix.app/Contents/document.wflow`.

You need to allow the app in Accessibility in Privaci tab in Security & Privacy settings pane.

**Comment by Alexays** [comment]
You can also press the `Print screen` button, don't know why ^^

**Comment by Hologos** [comment]
I will try it next time. Thanks

**Comment by Hologos** [comment]
I will migrate to https://github.com/acidanthera/VoodooPS2.

**Comment by Hologos** [comment]
It seems the problem disappeared.

**Comment by joeyave** [comment]
The same issue on lenovo laptop. Where can I download TrackpadFix.app?

**Comment by Hologos** [comment]
> The same issue on lenovo laptop.

Just press **Print screen** key and it works again.

> Where can I download TrackpadFix.app?

Since the fix is easier fixed with the **Print screen** key, I didn't update the app for macOS Catalina.

**Comment by jandersonthegreat** [comment]
print screen fix does not work on Big Sur.  Occasionally my trackpad stops working and it's getting annoying.  Perhaps update now?

**Comment by Mifaxav** [comment]
having the same problem on a lenovo T480. check my repo for the EFI
