### ISSUE TITLE
catalina 10.15.1 battery not show percentage

### ISSUE THREAD

**Issue by yjm9898** [Hologos/hackintosh-hp-elitebook-840-g3#6]
catalina 10.15.1 battery not show percentage

**Comment by Hologos** [comment]
It's working ok for me. Do you have **_Show battery percentage_** in the Settings?

![Snímek obrazovky 2019-11-12 v 14 11 46](https://user-images.githubusercontent.com/1620004/68674608-77980800-0556-11ea-85cd-da06326fffc3.png)
![Snímek obrazovky 2019-11-12 v 14 12 08](https://user-images.githubusercontent.com/1620004/68674685-a615e300-0556-11ea-9793-f25c8734431f.png)

**Comment by yjm9898** [comment]
![image](https://user-images.githubusercontent.com/7345830/68675860-bd26f600-0593-11ea-8c2e-71c5cd58df26.png)

**Comment by Hologos** [comment]
What's the output of `kextstat | grep -i battery`?

**Comment by yjm9898** [comment]
➜  ~ kextstat | grep -i battery
   64    0 0xffffff7f84671000 0x9000     0x9000     org.rehabman.driver.AppleSmartBatteryManager (1.90) 0EE476DC-884B-35FF-BD9E-E24BEC25A521 <12 5 3>

**Comment by Hologos** [comment]
I got 1.90.1 but I don't think that's the issue. I also found this

> Slow boot with APFS: This also leads to battery status being removed from the menu bar, and SysPrefs->Trackpad not showing the prefpane. With certain SSDs, TRIM patch, plus APFS leads to this problem. Solution: Disable the TRIM patch in config.plist or install on HFS+J instead of APFS.

> Slow boot causing battery status issues on APFS and 10.13+: If you have installed APFS (you have SSD), and the laptop seems to boot slower than expected, battery status is affected by this slow boot. Disable the TRIM patch in your config.plist as TRIM often has an issue with APFS on certain hardware.


Can you confirm?

**Comment by Hologos** [comment]
Also, do you have these patches included in your `config.plist` under `ACPI -> DSDT -> Patches` ?

```
<dict>
        <key>Comment</key>
        <string>change Notify(\_SB.BAT0,...) to Notify(_SB.BATC,...)</string>
        <key>Find</key>
        <data>hlwuX1NCX0JBVDA=</data>
        <key>Replace</key>
        <data>hlwuX1NCX0JBVEM=</data>
</dict>
<dict>
        <key>Comment</key>
        <string>change Notify(\_SB.BAT1,...) to Notify(_SB.BATC,...)</string>
        <key>Find</key>
        <data>hlwuX1NCX0JBVDE=</data>
        <key>Replace</key>
        <data>hlwuX1NCX0JBVEM=</data>
</dict>
<dict>
        <key>Comment</key>
        <string>change Notify(BAT0,...) to Notify(BATC,...)</string>
        <key>Find</key>
        <data>hkJBVDA=</data>
        <key>Replace</key>
        <data>hkJBVEM=</data>
</dict>
<dict>
        <key>Comment</key>
        <string>change Notify(BAT1,...) to Notify(BATC,...)</string>
        <key>Find</key>
        <data>hkJBVDE=</data>
        <key>Replace</key>
        <data>hkJBVEM=</data>
</dict>
```

**Comment by yjm9898** [comment]
> <dict>
>         <key>Comment</key>
>         <string>change Notify(\_SB.BAT0,...) to Notify(_SB.BATC,...)</string>
>         <key>Find</key>
>         <data>hlwuX1NCX0JBVDA=</data>
>         <key>Replace</key>
>         <data>hlwuX1NCX0JBVEM=</data>
> </dict>
> <dict>
>         <key>Comment</key>
>         <string>change Notify(\_SB.BAT1,...) to Notify(_SB.BATC,...)</string>
>         <key>Find</key>
>         <data>hlwuX1NCX0JBVDE=</data>
>         <key>Replace</key>
>         <data>hlwuX1NCX0JBVEM=</data>
> </dict>
> <dict>
>         <key>Comment</key>
>         <string>change Notify(BAT0,...) to Notify(BATC,...)</string>
>         <key>Find</key>
>         <data>hkJBVDA=</data>
>         <key>Replace</key>
>         <data>hkJBVEM=</data>
> </dict>
> <dict>
>         <key>Comment</key>
>         <string>change Notify(BAT1,...) to Notify(BATC,...)</string>
>         <key>Find</key>
>         <data>hkJBVDE=</data>
>         <key>Replace</key>
>         <data>hkJBVEM=</data>
> </dict>

![image](https://user-images.githubusercontent.com/7345830/68677218-a930c380-0596-11ea-923a-0d4e922d2537.png)
I checkout you git repo 10.15.1 branch efi

**Comment by Hologos** [comment]
1. Did you start from fresh when you downloaded my EFI?
2. Can you post output of `ls -l /Library/Extensions`?

**Comment by yjm9898** [comment]
> 1. Did you start from fresh when you downloaded my EFI?
> 2. Can you post output of `ls -l /Library/Extensions`?

- 
i have git pull the latest version into my efi .


`drwxr-xr-x  3 root  wheel  96 Apr 16  2019 ACS6x.kext
drwxr-xr-x  3 root  wheel  96 May  9  2018 ATTOCelerityFC8.kext
drwxr-xr-x  3 root  wheel  96 May  7  2018 ATTOExpressSASHBA2.kext
drwxr-xr-x  3 root  wheel  96 May  7  2018 ATTOExpressSASRAID2.kext
drwxr-xr-x@ 3 root  wheel  96 Mar 20  2019 AppleMobileDevice.kext
drwxr-xr-x  3 root  wheel  96 Aug 19 11:33 ArcMSR.kext
drwxr-xr-x  3 root  wheel  96 Sep  1  2013 CalDigitHDProDrv.kext
drwxr-xr-x  3 root  wheel  96 May  4  2018 HighPointIOP.kext
drwxr-xr-x  3 root  wheel  96 Dec  5  2017 HighPointRR.kext
drwxr-xr-x  3 root  wheel  96 Jul 26 18:36 PromiseSTEX.kext
drwxr-xr-x  3 root  wheel  96 Aug  9  2018 SoftRAID.kext`



![image](https://user-images.githubusercontent.com/7345830/68679744-6e7d5a00-059b-11ea-87c8-2423a0c16dc9.png)

**Comment by yjm9898** [comment]
> Solution: Disable the TRIM patch in config.plist or install on HFS+J instead of APFS.

I have remove the TRIM in the config.plist.  then restart cause kernel panic.

**Comment by Hologos** [comment]
Rebuild cache, restart and post the battery kext version from `kextstat` like before.

```bash
sudo mount -uw /
sudo chown -v -R root:wheel /System/Library/Extensions
sudo touch /System/Library/Extensions
sudo chmod -v -R 755 /Library/Extensions
sudo chown -v -R root:wheel /Library/Extensions
sudo touch /Library/Extensions
sudo kextcache -i /
```

**Comment by Hologos** [comment]
> I have remove the TRIM in the config.plist. then restart cause kernel panic.

How did you remove it? Can you post config.plist with removed TRIM patch? It shouldn't kernel panic.

**Comment by yjm9898** [comment]
> Rebuild cache, restart and post the battery kext version from `kextstat` like before.
> 
> ```shell
> sudo mount -uw /
> sudo chown -v -R root:wheel /System/Library/Extensions
> sudo touch /System/Library/Extensions
> sudo chmod -v -R 755 /Library/Extensions
> sudo chown -v -R root:wheel /Library/Extensions
> sudo touch /Library/Extensions
> sudo kextcache -i /
> ```

Thx. Done
